version: '3.3'
services:
  tyk-gateway:
    image: tykio/tyk-gateway:v4.1rc26
    ports:
      - 8080:8080
    networks:
      tyk:
    environment:
      - TYK_LOGLEVEL=${GATEWAY_LOGLEVEL:-info}
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
      - TYK_GW_TRACER_ENABLED=${TRACING_ENABLED:-false}
      - TYK_GW_HTTPSERVEROPTIONS_ENABLEHTTP2=true
      - TYK_GW_PROXYENABLEHTTP2=true
      - TYK_GW_HTTPSERVEROPTIONS_FLUSHINTERVAL=1
      - TYK_GW_ANALYTICSCONFIG_ENABLEGEOIP=true
    env_file:
    - .env
    volumes:
      - ./deployments/tyk-gateway/apps:/opt/tyk-gateway/apps
      - ./deployments/tyk-gateway/tyk.conf:/opt/tyk-gateway/tyk.conf
    depends_on:
      - tyk-redis

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.7.0-rc1
    ports:
    - 8083:8083
    - 8084:8084
    networks:
      - tyk
    volumes:
      - ./deployments/tyk-pump/pump.conf:/opt/tyk-pump/pump.conf
    environment:
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
      - TYK_LOGLEVEL=${PUMP_LOGLEVEL:-info}
    env_file:
    - .env
    depends_on:
      - tyk-redis
  
  tyk-redis:
    image: redis:6.0.4
    ports:
      - "6379:6379"
    volumes:
      - tyk-redis-data:/data
    networks:
      - tyk

  prometheus:
    image: prom/prometheus
    volumes:
      - ./deployments/prometheus/:/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - "9090:9090"
    networks:
      - tyk

  k6:
    image: grafana/k6:latest
    networks:
      - tyk
    ports:
      - "6565:6565"
    volumes:
      - ./deployments/k6/:/scripts

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./deployments/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./deployments/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
      - ./data/grafana/:/var/lib/grafana
    networks:
      - tyk
      

volumes:
  tyk-redis-data:
  grafana-data:

networks:
  tyk:
